urls = [
    "https://www.speedtest.net/performance/greece/attica/acharnes",
    "https://www.speedtest.net/performance/greece/attica/agia-paraskevi",
    "https://www.speedtest.net/performance/greece/attica/agia-varvara",
    "https://www.speedtest.net/performance/greece/attica/agioi-anargyroi",
    "https://www.speedtest.net/performance/greece/attica/agios-dimitrios",
    "https://www.speedtest.net/performance/greece/attica/agios-ioannis-rentis",
    "https://www.speedtest.net/performance/greece/attica/alimos",
    "https://www.speedtest.net/performance/greece/attica/anixi",
    "https://www.speedtest.net/performance/greece/attica/ano-liosia",
    "https://www.speedtest.net/performance/greece/attica/argyroupoli",
    # "https://www.speedtest.net/performance/greece/attica/artemida",
    # "https://www.speedtest.net/performance/greece/attica/athens",
    # "https://www.speedtest.net/performance/greece/attica/chaidari",
    # "https://www.speedtest.net/performance/greece/attica/chalandri",
    # "https://www.speedtest.net/performance/greece/attica/cholargos",
    # "https://www.speedtest.net/performance/greece/attica/dafni",
    # "https://www.speedtest.net/performance/greece/attica/drapetsona",
    # "https://www.speedtest.net/performance/greece/attica/egaleo",
    # "https://www.speedtest.net/performance/greece/attica/ekali",
    # "https://www.speedtest.net/performance/greece/attica/elefsina",
    # "https://www.speedtest.net/performance/greece/attica/elliniko",
    # "https://www.speedtest.net/performance/greece/attica/filothei",
    # "https://www.speedtest.net/performance/greece/attica/galatsi",
    # "https://www.speedtest.net/performance/greece/attica/gerakas",
    # "https://www.speedtest.net/performance/greece/attica/glyfada",
    # "https://www.speedtest.net/performance/greece/attica/glyka-nera",
    # "https://www.speedtest.net/performance/greece/attica/ilion",
    # "https://www.speedtest.net/performance/greece/attica/ilioupoli",
    # "https://www.speedtest.net/performance/greece/attica/iraklio",
    # "https://www.speedtest.net/performance/greece/attica/kallithea",
    # "https://www.speedtest.net/performance/greece/attica/kalyvia-thorikou",
    # "https://www.speedtest.net/performance/greece/attica/kamatero",
    # "https://www.speedtest.net/performance/greece/attica/keratsini",
    # "https://www.speedtest.net/performance/greece/attica/kesariani",
    # "https://www.speedtest.net/performance/greece/attica/kifisia",
    # "https://www.speedtest.net/performance/greece/attica/koropi",
    # "https://www.speedtest.net/performance/greece/attica/korydallos",
    # "https://www.speedtest.net/performance/greece/attica/marousi",
    # "https://www.speedtest.net/performance/greece/attica/megara",
    # "https://www.speedtest.net/performance/greece/attica/melissia",
    # "https://www.speedtest.net/performance/greece/attica/metamorfosi",
    # "https://www.speedtest.net/performance/greece/attica/moschato",
    # "https://www.speedtest.net/performance/greece/attica/nea-chalkidona",
    # "https://www.speedtest.net/performance/greece/attica/nea-erythraia",
    # "https://www.speedtest.net/performance/greece/attica/nea-filadelfeia",
    # "https://www.speedtest.net/performance/greece/attica/nea-ionia",
    # "https://www.speedtest.net/performance/greece/attica/nea-makri",
    # "https://www.speedtest.net/performance/greece/attica/nea-smyrni",
    # "https://www.speedtest.net/performance/greece/attica/neo-psychiko",
    # "https://www.speedtest.net/performance/greece/attica/nikaia",
    # "https://www.speedtest.net/performance/greece/attica/paiania",
    # "https://www.speedtest.net/performance/greece/attica/palaio-faliro",
    # "https://www.speedtest.net/performance/greece/attica/pallini",
    # "https://www.speedtest.net/performance/greece/attica/papagou",
    # "https://www.speedtest.net/performance/greece/attica/pefki",
    # "https://www.speedtest.net/performance/greece/attica/perama",
    # "https://www.speedtest.net/performance/greece/attica/peristeri",
    # "https://www.speedtest.net/performance/greece/attica/petroupoli",
    # "https://www.speedtest.net/performance/greece/attica/pireas",
    # "https://www.speedtest.net/performance/greece/attica/porto-rafti",
    # "https://www.speedtest.net/performance/greece/attica/psychiko",
    # "https://www.speedtest.net/performance/greece/attica/rafina",
    # "https://www.speedtest.net/performance/greece/attica/spata",
    # "https://www.speedtest.net/performance/greece/attica/tavros",
    # "https://www.speedtest.net/performance/greece/attica/vari",
    # "https://www.speedtest.net/performance/greece/attica/voula",
    # "https://www.speedtest.net/performance/greece/attica/vrilissia",
    # "https://www.speedtest.net/performance/greece/attica/vyronas",
    # "https://www.speedtest.net/performance/greece/attica/ymittos",
    # "https://www.speedtest.net/performance/greece/attica/zografou",
]
